package com.example.kanjilearning.data.model

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * VI: Entity đại diện cho 1 Kanji lưu trong bảng Room.
 * EN: Simple Room entity describing a Kanji row.
 */
@Entity(tableName = "kanjis")
data class KanjiEntity(
    /**
     * VI: Khoá chính tự tăng để Room quản lý.
     * EN: Primary key autogenerated by Room.
     */
    @PrimaryKey(autoGenerate = true)
    val id: Int = 0,
    /** VI: Chữ Kanji. EN: Kanji character. */
    @ColumnInfo(name = "word")
    val word: String,
    /** VI: Nghĩa tiếng Việt/Anh. EN: Kanji meaning description. */
    @ColumnInfo(name = "meaning")
    val meaning: String
)
